apiVersion: v1
kind: Service
metadata:
  name: springboot-k8s-demo-service
spec:
  selector:
      app: springboot-k8s-demo
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running inside the cluster
      targetPort: 8080 # The port exposed by the service
  type: NodePort # Use NodePort for local testing or LoadBalancer for cloud environments
