services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=password' # Big head
    ports:
      - '5432:5432'
    volumes:
      - './src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql'