receivers:
  otlp:
    protocols:
      http:

processors:
  batch:

exporters:
  logging:
    loglevel: debug

  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      label1: value1

  zipkin:
    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
    format: proto

  jaeger:
    endpoint: "http://jaeger-all-in-one:14250"
    tls:
      insecure: true

  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true

extensions:
  # Responsible for responding to health checks on behalf of collector
  health_check:
  # Fetches collectors performance data
  pprof:
  # Serves as HTTP endpoint that provides live debugging data about instrumented application
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, zipkin, jaeger, otlp]