spring:
  application:
    name: spring4observability

management:
  tracing:
    sampling:
      probability: 1.0 # 100% sampling for development

server:
  shutdown: immediate

logging:
  level:
    com.varunu28.spring4observability: INFO
    org.springframework.boot.actuator.autoconfigure.opentelemetry: DEBUG
    org.springframework.boot.docker.compose: DEBUG
