apiVersion: v1
kind: Pod
metadata:
  name: spring-app-pod
  labels:
    app: spring-app
spec:
  containers:
    - name: spring-app
      image: k8s-demo:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
