services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    volumes:
      - ./src/main/resources/script.sql:/docker-entrypoint-initdb.d/script.sql
    ports:
      - '5432:5432'
