services:
  postgres:
    image: 'postgres:15.3'
    container_name: test-postgres
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5433:5432'
    volumes:
      - ./postgres_scripts:/docker-entrypoint-initdb.d:ro
      - pgdata:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
    driver: local